# Generated by Django 2.1.5 on 2019-02-01 17:46

from django.conf import settings
import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck to hide the attachment from other users', verbose_name='is public')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date/time created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date/time modified')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='description')),
                ('attachment', models.FileField(db_index=True, upload_to=files.models.get_upload_to, verbose_name='attachment')),
                ('blob', files.models.BlobField(blank=True, editable=False, null=True, verbose_name='binary data')),
                ('backend', models.CharField(default=files.models.get_storate_name, editable=False, max_length=100)),
                ('mimetype', models.CharField(blank=True, max_length=50, null=True, verbose_name='mime type')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True)),
                ('size', models.PositiveIntegerField(blank=True, editable=False, verbose_name='file size')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=32, verbose_name='md5 checksum')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_attachment', to='contenttypes.ContentType', verbose_name='content type')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_attachments', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('site', models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'permissions': (('can_moderate', 'Can moderate attachments'), ('delete_all_attachment', 'Can delete all attachments'), ('download_attachment', 'Can download attachment')),
                'ordering': ('created', 'modified'),
            },
        ),
    ]
